root_path: 'my_path'
channels_file: 'my_channels_list.txt'
api_id: 'my_api_id'
api_hash: 'my_api_hash'
test: 'my_test'
test_public_key: 'my_test_key'
prod: 'my_prod'
prod_public_key: 'my_prod_key'
phone: 'my_phone'
user: 'my_user'